# This watches the L1 SystemConfig for OP Mainnet for config updates.
# - eth/op/SystemConfig
version: 1.0
name: SystemConfig Config Updates
priority: P2
addresses: # /!\ We are not supporting EIP 3770 yet, if the address is not starting by 0x, this will panic by safety measure.
events:
  - signature: ConfigUpdate(uint256 indexed version, UpdateType indexed updateType, bytes data)
  # Notice that the above signature is not normalized. The normalized version is:
  #   ConfigUpdate(uint256,uint8,bytes)
  # But for UX
