name: Pull Request Target Action

on:
  pull_request_target:
    branches:
          - test_branch
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello World
        run: echo "Hello, World!"
