name: Pull Request Target Action

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello World
        run: echo "Hello, World!"
